name: Terraform Plan
on:
  pull_request:
    paths: ["terraform/**"]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform init -backend=false
      - run: terraform -chdir=terraform validate
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with: { working_directory: terraform }
